apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: jxgo
    meta.helm.sh/release-namespace: jx-git-operator
  creationTimestamp: "2021-09-02T14:25:46Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: jx-git-operator-0.0.177
  name: jx-git-operator
  namespace: jx-git-operator
  resourceVersion: "1548"
  uid: cfc3b002-49bb-47a9-83f1-678b40e82f14
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jx-git-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jx-git-operator
    spec:
      containers:
      - args:
        - echo 'no custom git initialisation scripts'; jx-git-operator
        command:
        - /bin/sh
        - -c
        env:
        - name: POLL_DURATION
          value: 20s
        envFrom:
        - secretRef:
            name: jx-boot-job-env-vars
            optional: true
        image: reg.docker.alibaba-inc.com/search_cicd/jx-git-operator:0.0.177
        imagePullPolicy: Always
        name: jx-git-operator
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jx-git-operator
      serviceAccountName: jx-git-operator
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-09-02T14:25:46Z"
    lastUpdateTime: "2021-09-02T14:25:46Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-09-02T14:35:47Z"
    lastUpdateTime: "2021-09-02T14:35:47Z"
    message: ReplicaSet "jx-git-operator-7965dbcb55" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
